//Item Tags
onEvent('item.tags', event => {

    //Diamond
    event.removeAll('forge:ores/diamond')
    event.removeAll('forge:dusts/diamond')
    event.add('forge:dusts/diamond', 'emendatusenigmatica:diamond_dust')
    event.add('forge:ores/diamond', 'emendatusenigmatica:diamond_chunk')
    //Coal
    event.removeAll('forge:ores/coal')
    event.add('forge:ores/coal', 'emendatusenigmatica:coal_chunk')
    //Lapis
    event.removeAll('forge:ores/lapis')
    event.add('forge:ores/lapis', 'emendatusenigmatica:lapis_chunk')
    //Redstone
    event.removeAll('forge:ores/redstone')
    event.add('forge:ores/redstone', 'emendatusenigmatica:redstone_chunk')
    //Emerald
    event.removeAll('forge:ores/emerald')
    event.add('forge:ores/emerald', 'emendatusenigmatica:emerald_chunk')
    //Iron
    event.removeAll('forge:ores/iron')
    event.removeAll('forge:rods/iron')
    event.removeAll('forge:plates/iron')
    event.removeAll('forge:dusts/iron')
    event.add('forge:ores/iron', 'emendatusenigmatica:iron_chunk')
    event.add('forge:rods/iron', 'emendatusenigmatica:iron_rod')
    event.add('forge:plates/iron', 'emendatusenigmatica:iron_plate')
    event.add('forge:dusts/iron', 'emendatusenigmatica:iron_dust')
    //Gold
    event.removeAll('forge:ores/gold')
    event.removeAll('forge:rods/gold')
    event.removeAll('forge:plates/gold')
    event.removeAll('forge:dusts/gold')
    event.add('forge:ores/gold', 'emendatusenigmatica:gold_chunk')
    event.add('forge:rods/gold', 'emendatusenigmatica:gold_rod')
    event.add('forge:plates/gold', 'emendatusenigmatica:gold_plate')
    event.add('forge:dusts/gold', 'emendatusenigmatica:gold_dust')
    //Copper
    event.removeAll('forge:ingots/copper')
    event.removeAll('forge:storage_blocks/copper')
    event.removeAll('forge:nuggets/copper')
    event.removeAll('forge:ores/copper')
    event.removeAll('forge:rods/copper')
    event.removeAll('forge:plates/copper')
    event.removeAll('forge:dusts/copper')
    event.add('forge:ingots/copper', 'emendatusenigmatica:copper_ingot')
    event.add('forge:storage_blocks/copper', 'emendatusenigmatica:copper_block')
    event.add('forge:nuggets/copper', 'emendatusenigmatica:copper_nugget')
    event.add('forge:ores/copper', 'emendatusenigmatica:copper_chunk')
    event.add('forge:rods/copper', 'emendatusenigmatica:copper_rod')
    event.add('forge:plates/copper', 'emendatusenigmatica:copper_plate')
    event.add('forge:dusts/copper', 'emendatusenigmatica:copper_dust')
    //Zinc
    event.removeAll('forge:ingots/zinc')
    event.removeAll('forge:storage_blocks/zinc')
    event.removeAll('forge:nuggets/zinc')
    event.removeAll('forge:ores/zinc')
    event.removeAll('forge:rods/zinc')
    event.removeAll('forge:plates/zinc')
    event.removeAll('forge:dusts/zinc')
    event.add('forge:ingots/zinc', 'emendatusenigmatica:zinc_ingot')
    event.add('forge:storage_blocks/zinc', 'emendatusenigmatica:zinc_block')
    event.add('forge:nuggets/zinc', 'emendatusenigmatica:zinc_nugget')
    event.add('forge:ores/zinc', 'emendatusenigmatica:zinc_chunk')
    event.add('forge:rods/zinc', 'emendatusenigmatica:zinc_rod')
    event.add('forge:plates/zinc', 'emendatusenigmatica:zinc_plate')
    event.add('forge:dusts/zinc', 'emendatusenigmatica:zinc_dust')
    //Brass
    event.removeAll('forge:ingots/brass')
    event.removeAll('forge:storage_blocks/brass')
    event.removeAll('forge:nuggets/brass')
    event.removeAll('forge:plates/brass')
    event.removeAll('forge:rods/brass')
    event.add('forge:ingots/brass', 'emendatusenigmatica:brass_ingot')
    event.add('forge:storage_blocks/brass', 'emendatusenigmatica:brass_block')
    event.add('forge:nuggets/brass', 'emendatusenigmatica:brass_nugget')
    event.add('forge:plates/brass', 'emendatusenigmatica:brass_plate')
    event.add('forge:rods/brass', 'emendatusenigmatica:brass_rod')
    //Silver
    event.removeAll('forge:ingots/silver')
    event.removeAll('forge:storage_blocks/silver')
    event.removeAll('forge:nuggets/silver')
    event.removeAll('forge:ores/silver')
    event.removeAll('forge:rods/silver')
    event.removeAll('forge:plates/silver')
    event.removeAll('forge:dusts/silver')
    event.add('forge:ingots/silver', 'emendatusenigmatica:silver_ingot')
    event.add('forge:storage_blocks/silver', 'emendatusenigmatica:silver_block')
    event.add('forge:nuggets/silver', 'emendatusenigmatica:silver_nugget')
    event.add('forge:ores/silver', 'emendatusenigmatica:silver_chunk')
    event.add('forge:rods/silver', 'emendatusenigmatica:silver_rod')
    event.add('forge:plates/silver', 'emendatusenigmatica:silver_plate')
    event.add('forge:dusts/silver', 'emendatusenigmatica:silver_dust')
    //Lead
    event.removeAll('forge:ingots/lead')
    event.removeAll('forge:storage_blocks/lead')
    event.removeAll('forge:nuggets/lead')
    event.removeAll('forge:ores/lead')
    event.removeAll('forge:rods/lead')
    event.removeAll('forge:plates/lead')
    event.removeAll('forge:dusts/lead')
    event.add('forge:ingots/lead', 'emendatusenigmatica:lead_ingot')
    event.add('forge:storage_blocks/lead', 'emendatusenigmatica:lead_block')
    event.add('forge:nuggets/lead', 'emendatusenigmatica:lead_nugget')
    event.add('forge:ores/lead', 'emendatusenigmatica:lead_chunk')
    event.add('forge:rods/lead', 'emendatusenigmatica:lead_rod')
    event.add('forge:plates/lead', 'emendatusenigmatica:lead_plate')
    event.add('forge:dusts/lead', 'emendatusenigmatica:lead_dust')
    //Obsidian
    event.removeAll('forge:dusts/obsidian')
    event.add('forge:dusts/obsidian', 'emendatusenigmatica:obsidian_dust')
    //Quartz
    event.removeAll('forge:ores/quartz')
    event.add('forge:ores/quartz', 'emendatusenigmatica:quartz_chunk')
    //Other ores
    event.removeAll('forge:ores/aluminum')
    event.removeAll('forge:ores/nickel')
    event.removeAll('forge:ores/uranium')
    event.removeAll('forge:ores/osmium')
    event.removeAll('forge:ores/tin')
    event.removeAll('forge:ores/certus_quartz')
    event.removeAll('forge:ores/charged_certus_quartz')
    event.removeAll('forge:ores/fluorite')
    event.removeAll('forge:ores/bitumen')
    event.removeAll('forge:ores/cinnabar')
    event.removeAll('forge:ores/apatite')
    event.removeAll('forge:ores/sulfur')
    event.removeAll('forge:ores/potassium_nitrate')
    event.removeAll('forge:ores/arcane')
    event.removeAll('forge:ores/dimensional')
    event.removeAll('forge:ores/cobalt')
    //Other Ingots
    event.removeAll('forge:ingots/aluminum')
    event.removeAll('forge:ingots/nickel')
    event.removeAll('forge:ingots/uranium')
    event.removeAll('forge:ingots/osmium')
    event.removeAll('forge:ingots/tin')
    event.removeAll('forge:ingots/certus_quartz')
    event.removeAll('forge:ingots/charged_certus_quartz')
    event.removeAll('forge:ingots/fluorite')
    event.removeAll('forge:ingots/bitumen')
    event.removeAll('forge:ingots/cinnabar')
    event.removeAll('forge:ingots/apatite')
    event.removeAll('forge:ingots/sulfur')
    event.removeAll('forge:ingots/potassium_nitrate')
    event.removeAll('forge:ingots/arcane')
    event.removeAll('forge:ingots/dimensional')
    event.removeAll('forge:ingots/cobalt')
    //Random
    event.remove('forge:grain/rice', 'environmental:rice')
    event.remove('forge:seeds/rice', 'environmental:rice')
    event.remove('forge:crops/rice', 'environmental:rice')
    event.remove('forge:grain', 'environmental:rice')
    event.remove('forge:crops', 'environmental:rice')
    event.remove('forge:seeds', 'environmental:rice')

    //Forge:ores
    //Cobalt
    event.remove('forge:ores', ['emendatusenigmatica:cobalt_ore', 'emendatusenigmatica:cobalt_andesite_ore', 'emendatusenigmatica:cobalt_granite_ore', 'emendatusenigmatica:cobalt_diorite_ore', 'emendatusenigmatica:cobalt_sand_ore', 'emendatusenigmatica:cobalt_gravel_ore', 'emendatusenigmatica:cobalt_netherrack_ore', 'emendatusenigmatica:cobalt_blackstone_ore', 'emendatusenigmatica:cobalt_basalt_ore', 'emendatusenigmatica:cobalt_soul_soil_ore', 'emendatusenigmatica:cobalt_end_stone_ore', 'emendatusenigmatica:cobalt_gabbro_ore', 'emendatusenigmatica:cobalt_c_limestone_ore', 'emendatusenigmatica:cobalt_scoria_ore', 'emendatusenigmatica:cobalt_weathered_limestone_ore', 'emendatusenigmatica:cobalt_jasper_ore', 'emendatusenigmatica:cobalt_marble_ore', 'emendatusenigmatica:cobalt_slate_ore', 'emendatusenigmatica:cobalt_mossy_stone_ore', 'emendatusenigmatica:cobalt_brimstone_ore', 'emendatusenigmatica:cobalt_subzero_ash_ore', 'emendatusenigmatica:cobalt_blue_netherrack_ore', 'emendatusenigmatica:cobalt_nylium_soul_soil_ore', 'emendatusenigmatica:cobalt_ether_stone_ore', 'emendatusenigmatica:cobalt_cryptic_stone_ore', 'emendatusenigmatica:cobalt_flavolite_ore', 'emendatusenigmatica:cobalt_sulphuric_rock_ore', 'emendatusenigmatica:cobalt_violecite_ore', 'emendatusenigmatica:cobalt_raw_marble_ore'])
    //Uranium
    event.remove('forge:ores', ['emendatusenigmatica:uranium_ore', 'emendatusenigmatica:uranium_andesite_ore', 'emendatusenigmatica:uranium_granite_ore', 'emendatusenigmatica:uranium_diorite_ore', 'emendatusenigmatica:uranium_sand_ore', 'emendatusenigmatica:uranium_gravel_ore', 'emendatusenigmatica:uranium_netherrack_ore', 'emendatusenigmatica:uranium_blackstone_ore', 'emendatusenigmatica:uranium_basalt_ore', 'emendatusenigmatica:uranium_soul_soil_ore', 'emendatusenigmatica:uranium_end_stone_ore', 'emendatusenigmatica:uranium_gabbro_ore', 'emendatusenigmatica:uranium_c_limestone_ore', 'emendatusenigmatica:uranium_scoria_ore', 'emendatusenigmatica:uranium_weathered_limestone_ore', 'emendatusenigmatica:uranium_jasper_ore', 'emendatusenigmatica:uranium_marble_ore', 'emendatusenigmatica:uranium_slate_ore', 'emendatusenigmatica:uranium_mossy_stone_ore', 'emendatusenigmatica:uranium_brimstone_ore', 'emendatusenigmatica:uranium_subzero_ash_ore', 'emendatusenigmatica:uranium_blue_netherrack_ore', 'emendatusenigmatica:uranium_nylium_soul_soil_ore', 'emendatusenigmatica:uranium_ether_stone_ore', 'emendatusenigmatica:uranium_cryptic_stone_ore', 'emendatusenigmatica:uranium_flavolite_ore', 'emendatusenigmatica:uranium_sulphuric_rock_ore', 'emendatusenigmatica:uranium_violecite_ore', 'emendatusenigmatica:uranium_raw_marble_ore'])
    //Apatite
    event.remove('forge:ores', ['emendatusenigmatica:apatite_ore', 'emendatusenigmatica:apatite_andesite_ore', 'emendatusenigmatica:apatite_granite_ore', 'emendatusenigmatica:apatite_diorite_ore', 'emendatusenigmatica:apatite_sand_ore', 'emendatusenigmatica:apatite_gravel_ore', 'emendatusenigmatica:apatite_netherrack_ore', 'emendatusenigmatica:apatite_blackstone_ore', 'emendatusenigmatica:apatite_basalt_ore', 'emendatusenigmatica:apatite_soul_soil_ore', 'emendatusenigmatica:apatite_end_stone_ore', 'emendatusenigmatica:apatite_gabbro_ore', 'emendatusenigmatica:apatite_c_limestone_ore', 'emendatusenigmatica:apatite_scoria_ore', 'emendatusenigmatica:apatite_weathered_limestone_ore', 'emendatusenigmatica:apatite_jasper_ore', 'emendatusenigmatica:apatite_marble_ore', 'emendatusenigmatica:apatite_slate_ore', 'emendatusenigmatica:apatite_mossy_stone_ore', 'emendatusenigmatica:apatite_brimstone_ore', 'emendatusenigmatica:apatite_subzero_ash_ore', 'emendatusenigmatica:apatite_blue_netherrack_ore', 'emendatusenigmatica:apatite_nylium_soul_soil_ore', 'emendatusenigmatica:apatite_ether_stone_ore', 'emendatusenigmatica:apatite_cryptic_stone_ore', 'emendatusenigmatica:apatite_flavolite_ore', 'emendatusenigmatica:apatite_sulphuric_rock_ore', 'emendatusenigmatica:apatite_violecite_ore', 'emendatusenigmatica:apatite_raw_marble_ore'])
    //Sulfur
    event.remove('forge:ores', ['emendatusenigmatica:sulfur_ore', 'emendatusenigmatica:sulfur_andesite_ore', 'emendatusenigmatica:sulfur_granite_ore', 'emendatusenigmatica:sulfur_diorite_ore', 'emendatusenigmatica:sulfur_sand_ore', 'emendatusenigmatica:sulfur_gravel_ore', 'emendatusenigmatica:sulfur_netherrack_ore', 'emendatusenigmatica:sulfur_blackstone_ore', 'emendatusenigmatica:sulfur_basalt_ore', 'emendatusenigmatica:sulfur_soul_soil_ore', 'emendatusenigmatica:sulfur_end_stone_ore', 'emendatusenigmatica:sulfur_gabbro_ore', 'emendatusenigmatica:sulfur_c_limestone_ore', 'emendatusenigmatica:sulfur_scoria_ore', 'emendatusenigmatica:sulfur_weathered_limestone_ore', 'emendatusenigmatica:sulfur_jasper_ore', 'emendatusenigmatica:sulfur_marble_ore', 'emendatusenigmatica:sulfur_slate_ore', 'emendatusenigmatica:sulfur_mossy_stone_ore', 'emendatusenigmatica:sulfur_brimstone_ore', 'emendatusenigmatica:sulfur_subzero_ash_ore', 'emendatusenigmatica:sulfur_blue_netherrack_ore', 'emendatusenigmatica:sulfur_nylium_soul_soil_ore', 'emendatusenigmatica:sulfur_ether_stone_ore', 'emendatusenigmatica:sulfur_cryptic_stone_ore', 'emendatusenigmatica:sulfur_flavolite_ore', 'emendatusenigmatica:sulfur_sulphuric_rock_ore', 'emendatusenigmatica:sulfur_violecite_ore', 'emendatusenigmatica:sulfur_raw_marble_ore'])
    //Nickel
    event.remove('forge:ores', ['emendatusenigmatica:nickel_ore', 'emendatusenigmatica:nickel_andesite_ore', 'emendatusenigmatica:nickel_granite_ore', 'emendatusenigmatica:nickel_diorite_ore', 'emendatusenigmatica:nickel_sand_ore', 'emendatusenigmatica:nickel_gravel_ore', 'emendatusenigmatica:nickel_netherrack_ore', 'emendatusenigmatica:nickel_blackstone_ore', 'emendatusenigmatica:nickel_basalt_ore', 'emendatusenigmatica:nickel_soul_soil_ore', 'emendatusenigmatica:nickel_end_stone_ore', 'emendatusenigmatica:nickel_gabbro_ore', 'emendatusenigmatica:nickel_c_limestone_ore', 'emendatusenigmatica:nickel_scoria_ore', 'emendatusenigmatica:nickel_weathered_limestone_ore', 'emendatusenigmatica:nickel_jasper_ore', 'emendatusenigmatica:nickel_marble_ore', 'emendatusenigmatica:nickel_slate_ore', 'emendatusenigmatica:nickel_mossy_stone_ore', 'emendatusenigmatica:nickel_brimstone_ore', 'emendatusenigmatica:nickel_subzero_ash_ore', 'emendatusenigmatica:nickel_blue_netherrack_ore', 'emendatusenigmatica:nickel_nylium_soul_soil_ore', 'emendatusenigmatica:nickel_ether_stone_ore', 'emendatusenigmatica:nickel_cryptic_stone_ore', 'emendatusenigmatica:nickel_flavolite_ore', 'emendatusenigmatica:nickel_sulphuric_rock_ore', 'emendatusenigmatica:nickel_violecite_ore', 'emendatusenigmatica:nickel_raw_marble_ore'])
    //Cinnabar
    event.remove('forge:ores', ['emendatusenigmatica:cinnabar_ore', 'emendatusenigmatica:cinnabar_andesite_ore', 'emendatusenigmatica:cinnabar_granite_ore', 'emendatusenigmatica:cinnabar_diorite_ore', 'emendatusenigmatica:cinnabar_sand_ore', 'emendatusenigmatica:cinnabar_gravel_ore', 'emendatusenigmatica:cinnabar_netherrack_ore', 'emendatusenigmatica:cinnabar_blackstone_ore', 'emendatusenigmatica:cinnabar_basalt_ore', 'emendatusenigmatica:cinnabar_soul_soil_ore', 'emendatusenigmatica:cinnabar_end_stone_ore', 'emendatusenigmatica:cinnabar_gabbro_ore', 'emendatusenigmatica:cinnabar_c_limestone_ore', 'emendatusenigmatica:cinnabar_scoria_ore', 'emendatusenigmatica:cinnabar_weathered_limestone_ore', 'emendatusenigmatica:cinnabar_jasper_ore', 'emendatusenigmatica:cinnabar_marble_ore', 'emendatusenigmatica:cinnabar_slate_ore', 'emendatusenigmatica:cinnabar_mossy_stone_ore', 'emendatusenigmatica:cinnabar_brimstone_ore', 'emendatusenigmatica:cinnabar_subzero_ash_ore', 'emendatusenigmatica:cinnabar_blue_netherrack_ore', 'emendatusenigmatica:cinnabar_nylium_soul_soil_ore', 'emendatusenigmatica:cinnabar_ether_stone_ore', 'emendatusenigmatica:cinnabar_cryptic_stone_ore', 'emendatusenigmatica:cinnabar_flavolite_ore', 'emendatusenigmatica:cinnabar_sulphuric_rock_ore', 'emendatusenigmatica:cinnabar_violecite_ore', 'emendatusenigmatica:cinnabar_raw_marble_ore'])
    //Osmium
    event.remove('forge:ores', ['emendatusenigmatica:osmium_ore', 'emendatusenigmatica:osmium_andesite_ore', 'emendatusenigmatica:osmium_granite_ore', 'emendatusenigmatica:osmium_diorite_ore', 'emendatusenigmatica:osmium_sand_ore', 'emendatusenigmatica:osmium_gravel_ore', 'emendatusenigmatica:osmium_netherrack_ore', 'emendatusenigmatica:osmium_blackstone_ore', 'emendatusenigmatica:osmium_basalt_ore', 'emendatusenigmatica:osmium_soul_soil_ore', 'emendatusenigmatica:osmium_end_stone_ore', 'emendatusenigmatica:osmium_gabbro_ore', 'emendatusenigmatica:osmium_c_limestone_ore', 'emendatusenigmatica:osmium_scoria_ore', 'emendatusenigmatica:osmium_weathered_limestone_ore', 'emendatusenigmatica:osmium_jasper_ore', 'emendatusenigmatica:osmium_marble_ore', 'emendatusenigmatica:osmium_slate_ore', 'emendatusenigmatica:osmium_mossy_stone_ore', 'emendatusenigmatica:osmium_brimstone_ore', 'emendatusenigmatica:osmium_subzero_ash_ore', 'emendatusenigmatica:osmium_blue_netherrack_ore', 'emendatusenigmatica:osmium_nylium_soul_soil_ore', 'emendatusenigmatica:osmium_ether_stone_ore', 'emendatusenigmatica:osmium_cryptic_stone_ore', 'emendatusenigmatica:osmium_flavolite_ore', 'emendatusenigmatica:osmium_sulphuric_rock_ore', 'emendatusenigmatica:osmium_violecite_ore', 'emendatusenigmatica:osmium_raw_marble_ore'])
    //Tin
    event.remove('forge:ores', ['emendatusenigmatica:tin_ore', 'emendatusenigmatica:tin_andesite_ore', 'emendatusenigmatica:tin_granite_ore', 'emendatusenigmatica:tin_diorite_ore', 'emendatusenigmatica:tin_sand_ore', 'emendatusenigmatica:tin_gravel_ore', 'emendatusenigmatica:tin_netherrack_ore', 'emendatusenigmatica:tin_blackstone_ore', 'emendatusenigmatica:tin_basalt_ore', 'emendatusenigmatica:tin_soul_soil_ore', 'emendatusenigmatica:tin_end_stone_ore', 'emendatusenigmatica:tin_gabbro_ore', 'emendatusenigmatica:tin_c_limestone_ore', 'emendatusenigmatica:tin_scoria_ore', 'emendatusenigmatica:tin_weathered_limestone_ore', 'emendatusenigmatica:tin_jasper_ore', 'emendatusenigmatica:tin_marble_ore', 'emendatusenigmatica:tin_slate_ore', 'emendatusenigmatica:tin_mossy_stone_ore', 'emendatusenigmatica:tin_brimstone_ore', 'emendatusenigmatica:tin_subzero_ash_ore', 'emendatusenigmatica:tin_blue_netherrack_ore', 'emendatusenigmatica:tin_nylium_soul_soil_ore', 'emendatusenigmatica:tin_ether_stone_ore', 'emendatusenigmatica:tin_cryptic_stone_ore', 'emendatusenigmatica:tin_flavolite_ore', 'emendatusenigmatica:tin_sulphuric_rock_ore', 'emendatusenigmatica:tin_violecite_ore', 'emendatusenigmatica:tin_raw_marble_ore'])
    //Aluminum
    event.remove('forge:ores', ['emendatusenigmatica:aluminum_ore', 'emendatusenigmatica:aluminum_andesite_ore', 'emendatusenigmatica:aluminum_granite_ore', 'emendatusenigmatica:aluminum_diorite_ore', 'emendatusenigmatica:aluminum_sand_ore', 'emendatusenigmatica:aluminum_gravel_ore', 'emendatusenigmatica:aluminum_netherrack_ore', 'emendatusenigmatica:aluminum_blackstone_ore', 'emendatusenigmatica:aluminum_basalt_ore', 'emendatusenigmatica:aluminum_soul_soil_ore', 'emendatusenigmatica:aluminum_end_stone_ore', 'emendatusenigmatica:aluminum_gabbro_ore', 'emendatusenigmatica:aluminum_c_limestone_ore', 'emendatusenigmatica:aluminum_scoria_ore', 'emendatusenigmatica:aluminum_weathered_limestone_ore', 'emendatusenigmatica:aluminum_jasper_ore', 'emendatusenigmatica:aluminum_marble_ore', 'emendatusenigmatica:aluminum_slate_ore', 'emendatusenigmatica:aluminum_mossy_stone_ore', 'emendatusenigmatica:aluminum_brimstone_ore', 'emendatusenigmatica:aluminum_subzero_ash_ore', 'emendatusenigmatica:aluminum_blue_netherrack_ore', 'emendatusenigmatica:aluminum_nylium_soul_soil_ore', 'emendatusenigmatica:aluminum_ether_stone_ore', 'emendatusenigmatica:aluminum_cryptic_stone_ore', 'emendatusenigmatica:aluminum_flavolite_ore', 'emendatusenigmatica:aluminum_sulphuric_rock_ore', 'emendatusenigmatica:aluminum_violecite_ore', 'emendatusenigmatica:aluminum_raw_marble_ore'])
})