// priority: 1000000
onEvent('block.registry', event => {
  //Aridrock
  event.create('momo:aridrock_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Aridrock Copper Ore')
  event.create('momo:aridrock_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Aridrock Zinc Ore')
  //Limerock
  event.create('momo:rhyolite_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Rhyolite Copper Ore')
  event.create('momo:rhyolite_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Rhyolite Zinc Ore')
  //Shale
  event.create('momo:shale_coal_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 1).displayName('Shale Coal Ore')
  event.create('momo:shale_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Copper Ore')
  event.create('momo:shale_diamond_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Diamond Ore')
  event.create('momo:shale_emerald_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Emerald Ore')
  event.create('momo:shale_gold_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Gold Ore')
  event.create('momo:shale_iron_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Iron Ore')
  event.create('momo:shale_lapis_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Lapis Lazuli Ore')
  event.create('momo:shale_redstone_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Redstone Ore')
  event.create('momo:shale_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Shale Zinc Ore')
  //Grimestone
  event.create('momo:grimestone_coal_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 1).displayName('Grimestone Coal Ore')
  event.create('momo:grimestone_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Copper Ore')
  event.create('momo:grimestone_diamond_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Diamond Ore')
  event.create('momo:grimestone_emerald_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Emerald Ore')
  event.create('momo:grimestone_gold_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Gold Ore')
  event.create('momo:grimestone_iron_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Iron Ore')
  event.create('momo:grimestone_lapis_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Lapis Lazuli Ore')
  event.create('momo:grimestone_redstone_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Redstone Ore')
  event.create('momo:grimestone_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Grimestone Zinc Ore')
  //Dolomite
  event.create('momo:dolomite_coal_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 1).displayName('Dolomite Coal Ore')
  event.create('momo:dolomite_copper_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Copper Ore')
  event.create('momo:dolomite_diamond_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Diamond Ore')
  event.create('momo:dolomite_emerald_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Emerald Ore')
  event.create('momo:dolomite_gold_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Gold Ore')
  event.create('momo:dolomite_iron_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Iron Ore')
  event.create('momo:dolomite_lapis_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Lapis Lazuli Ore')
  event.create('momo:dolomite_redstone_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Redstone Ore')
  event.create('momo:dolomite_zinc_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Dolomite Zinc Ore')
  //Gabbro
  event.create('momo:gabbro_coal_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 1).displayName('Gabbro Coal Ore')
  event.create('momo:gabbro_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Copper Ore')
  event.create('momo:gabbro_diamond_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Diamond Ore')
  event.create('momo:gabbro_emerald_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Emerald Ore')
  event.create('momo:gabbro_gold_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Gold Ore')
  event.create('momo:gabbro_iron_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Iron Ore')
  event.create('momo:gabbro_lapis_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Lapis Lazuli Ore')
  event.create('momo:gabbro_redstone_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Redstone Ore')
  event.create('momo:gabbro_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Gabbro Zinc Ore')
  //Scoria
  event.create('momo:scoria_coal_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 1).displayName('Scoria Coal Ore')
  event.create('momo:scoria_copper_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Copper Ore')
  event.create('momo:scoria_diamond_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Diamond Ore')
  event.create('momo:scoria_emerald_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Emerald Ore')
  event.create('momo:scoria_gold_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Gold Ore')
  event.create('momo:scoria_iron_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Iron Ore')
  event.create('momo:scoria_lapis_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Lapis Lazuli Ore')
  event.create('momo:scoria_redstone_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Redstone Ore')
  event.create('momo:scoria_zinc_ore').material('stone').hardness(3.0).harvestTool('pickaxe', 2).displayName('Scoria Zinc Ore')
  //Weathered Limestone
  event.create('momo:weathered_limestone_coal_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 1).displayName('Weathered Limestone Coal Ore')
  event.create('momo:weathered_limestone_copper_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Copper Ore')
  event.create('momo:weathered_limestone_diamond_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Diamond Ore')
  event.create('momo:weathered_limestone_emerald_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Emerald Ore')
  event.create('momo:weathered_limestone_gold_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Gold Ore')
  event.create('momo:weathered_limestone_iron_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Iron Ore')
  event.create('momo:weathered_limestone_lapis_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Lapis Lazuli Ore')
  event.create('momo:weathered_limestone_redstone_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Redstone Ore')
  event.create('momo:weathered_limestone_zinc_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Weathered Limestone Zinc Ore')
  //Limestone
  event.create('momo:limestone_coal_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 1).displayName('Limestone Coal Ore')
  event.create('momo:limestone_copper_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Copper Ore')
  event.create('momo:limestone_diamond_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Diamond Ore')
  event.create('momo:limestone_emerald_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Emerald Ore')
  event.create('momo:limestone_gold_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Gold Ore')
  event.create('momo:limestone_iron_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Iron Ore')
  event.create('momo:limestone_lapis_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Lapis Lazuli Ore')
  event.create('momo:limestone_redstone_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Redstone Ore')
  event.create('momo:limestone_zinc_ore').material('stone').hardness(2.5).harvestTool('pickaxe', 2).displayName('Limestone Zinc Ore')
  //Deepslate
  event.create('momo:deepslate_coal_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 1).displayName('Deepslate Coal Ore')
  event.create('momo:deepslate_copper_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Copper Ore')
  event.create('momo:deepslate_diamond_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Diamond Ore')
  event.create('momo:deepslate_emerald_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Emerald Ore')
  event.create('momo:deepslate_gold_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Gold Ore')
  event.create('momo:deepslate_iron_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Iron Ore')
  event.create('momo:deepslate_lapis_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Lapis Lazuli Ore')
  event.create('momo:deepslate_redstone_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Redstone Ore')
  event.create('momo:deepslate_zinc_ore').material('stone').hardness(4.5).harvestTool('pickaxe', 2).displayName('Deepslate Zinc Ore')
})
