//priority: 10000
onEvent('item.registry', event => {
  event.create('momo:hemolymph_pustules').displayName('Hemolymph Pustules').rarity(RARITY_EPIC)
  event.create('momo:lesser_ender_eye').displayName('Lesser Eye of Ender')
  event.create('momo:raw_coal').displayName('Raw Coal')
  event.create('momo:raw_copper').displayName('Raw Copper')
  event.create('momo:raw_diamond').displayName('Raw Diamond')
  event.create('momo:raw_emerald').displayName('Raw Emerald')
  event.create('momo:raw_gold').displayName('Raw Gold')
  event.create('momo:raw_iron').displayName('Raw Iron')
  event.create('momo:raw_lapis').displayName('Raw Lapis')
  event.create('momo:raw_redstone').displayName('Raw Redstone')
  event.create('momo:raw_zinc').displayName('Raw Zinc')
  event.create('momo:penguin_icon').displayName('Penguin Icon')
  event.create('momo:beach_crab_icon').displayName('Beach Crab Icon')
  event.create('momo:moth_icon').displayName('Moth Icon')
  event.create('momo:aquatic_catalyst1').displayName('Lesser Aquatic Catalyst')
  event.create('momo:aquatic_catalyst2').displayName('Aquatic Catalyst').rarity(RARITY_UNCOMMON)
  event.create('momo:aquatic_catalyst3').displayName('Great Aquatic Catalyst').rarity(RARITY_UNCOMMON)
  event.create('momo:aquatic_catalyst4').displayName('Greater Aquatic Catalyst').rarity(RARITY_RARE)
  event.create('momo:aquatic_catalyst5').displayName('Ultimate Aquatic Catalyst').rarity(RARITY_EPIC)
  event.create('momo:eternal_ingot').displayName('Eternal Ingot').rarity(RARITY_EPIC)
})