### Particle Image Function
### Version: 1.0.4
### Width: 15
### Height: 15
### ParticleType: flame

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:flame ^1.7333333 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.6 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:flame ^1.4666667 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.4666667 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:flame ^1.4666667 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.4666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.7333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.2 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.0666667 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:flame ^1.0666667 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.0666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.0666667 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.0666667 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^-0.6 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.9333333 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^-0.4666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.8 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.5333333 ^0 ^-0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.5333333 ^0 ^-0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.5333333 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.5333333 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.4 ^0 ^0.0666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.4 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.2666667 ^0 ^0.2 0 0 0 0 1 force @a
particle minecraft:flame ^0.2666667 ^0 ^0.4666667 0 0 0 0 1 force @a
