### Particle Image Function
### Version: 1.0.4
### Width: 12
### Height: 12
### ParticleType: flame

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:flame ^1.6666667 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:flame ^1.5 ^0 ^-0.6666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.5 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^-0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:flame ^1.3333333 ^0 ^0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.1666667 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:flame ^1.1666667 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1.1666667 ^0 ^-0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1.1666667 ^0 ^0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^-0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^1 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.8333333 ^0 ^-0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.8333333 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:flame ^0.8333333 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^-0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.6666667 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.5 ^0 ^0.1666667 0 0 0 0 1 force @a
particle minecraft:flame ^0.5 ^0 ^0.3333333 0 0 0 0 1 force @a
particle minecraft:flame ^0.3333333 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:flame ^0.1666667 ^0 ^0.6666667 0 0 0 0 1 force @a
